smart-village-solutions/smart-village-app-mainserver

.codeclimate.yml
* config file specifies rubocop version and includes rspec file to be
linted
issue-7
=> Add Code Climate Config file to project

app/models/category.rb, db/migrate/20190429142017_add_ancestry_to_category.rb, db/schema.rb, spec/rails_helper.rb
* has_ancestry connects the category model to gem ancestry and oraganizes the model as a tree with root and children nodes
* to make this work a migration adds property ancestry with an index to categories table
#2
=> Organize model category as a tree

Gemfile, Gemfile.lock, spec/rails_helper.rb
* add gem simplecov for analysis of test coverage  for project
* add gem code climate test reporter to be able to send code coverage data from local app to codeclimate repo
#15
=> Add gems to be able to display test coverage for project

Gemfile, Gemfile.lock, app/models/point_of_interest.rb, config/initializers/taggable.rb, db/migrate/20190430150344_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb, db/migrate/20190430150345_add_missing_unique_indices.acts_as_taggable_on_engine.rb, db/migrate/20190430150346_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb, db/migrate/20190430150347_add_missing_taggable_index.acts_as_taggable_on_engine.rb, db/migrate/20190430150348_change_collation_for_tag_names.acts_as_taggable_on_engine.rb, db/migrate/20190430150349_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb, db/schema.rb
* act as taggable gives the model poi a taglist where tags which come
from the TMB.xml can be saved
#3
=> Add act_as_taggable to POI

app/models/content_block.rb, app/models/news_item.rb, db/migrate/20190502105044_create_news_items.rb, db/migrate/20190502105927_create_content_blocks.rb, spec/factories/content_blocks.rb, spec/factories/news_items.rb, spec/models/content_block_spec.rb, spec/models/news_item_spec.rb
* add basic model for news according to swagger specification
*  add basic model for content_blocks. Content blocks are the building blocks for news items
* spec the relations of both models and add factories for future specs
#8
=> Add basic model for news_items and connected content_blocks and spec it

app/graphql/types/contact_type.rb, app/models/contact.rb
* one contact can have many urls, so this commit will change its association to web url from has_one to has_many
#27
=> Change Web url association for contact

config/initializers/admin_user.rb
check if "users" table exist, otherwise the initial db setup breaks on init
=> only setup admin user if users table exists

app/graphql/mutations/create_point_of_interest.rb, app/graphql/types/point_of_interest_type.rb
=> fix poi tag_list type

app/graphql/types/address_type.rb, app/graphql/types/data_provider_input.rb, app/graphql/types/event_record_type.rb, app/graphql/types/geo_location_input.rb, app/graphql/types/news_item_type.rb, app/graphql/types/point_of_interest_type.rb, app/graphql/types/public_html_file_type.rb, app/graphql/types/tour_type.rb, app/graphql/types/web_url_type.rb
* graphql server has its own validation system
* a lot of queries had field who weren't allowed to return nil
* commit will undo this and remove all required arguments except for title and name arguments for the main resources
=> Remove unecessary argument and field validations

app/graphql/types/category_type.rb, app/graphql/types/event_record_type.rb, app/graphql/types/point_of_interest_type.rb, app/graphql/types/tour_type.rb
Replace category_id with category (CategoryType) on PointOfInterest, Tour and EventRecord
=> add category_type with id and name

public/mobile-app/contents/datenschutz.html, public/mobile-app/contents/impressum.html
- TODO  in Datenschutz  h5 needs to be turned in to a fit tag
=> Update HTML content of Impressum and Datenschutz

app/graphql/resolvers/points_of_interest_search.rb
* Add RAND to poi order type
* add resolver method which retrieves a drandom order/selection of Pois from database
When this pr is merged queries like this will be possible:
#79
=> Add posiibility to order pois randomly

db/migrate/20190626125951_add_default_value_to_use_only_time_description.rb, db/schema.rb
* add migration which adds default value false to use_only_time_description
#40
=> Add default value to fixed_date_column

app/models/point_of_interest.rb
* change price to price_informations for poi model because it is coherent
with event_record
#77
=> Change price to price_informations

app/graphql/resolvers/tours_search.rb
- added `RAND` to ToursOrder type
- added resolver method which retrieves a random
order/selection of Tours from database
fixes #107
=> Add possibility to order tours randomly

config/puma.rb, db/migrate/20190801100340_change_content_block_columns.rb, db/migrate/20190801102354_change_caption_text_to_be_text_in_media_contents.rb, db/schema.rb
* change columns from string to text where maz sends long texts instead of expected short strings
* recreate database
=> Bugfix for content columns

app/graphql/types/query_type.rb
* add field categories
* add resolver method catgories which returns all categories  ordered alphabetically
* query returns category type which means that subfields id and name are available
closes #112
=> Add query resolver for new categories field

app/services/resource_service.rb
- Error: undefined method `blank' for nil:NilClass
Did you mean?  blank?
- YES
- added missing question mark
=> Add missing ?

app/models/data_resources/event_record.rb, spec/models/event_record_spec.rb
- added return of "today" if a start and end date
describes a larger time range, which has not ended yet
-- this is only implemented for event records with one
date entry
-- future cases are possible to come
- added specs for different time range cases
=> Add logical case for list date of event records

config/initializers/devise.rb
Session expires now after 60 Minutes
=> feat: extend devise session timeout

app/graphql/resolvers/event_records_search.rb, app/models/data_resources/event_record.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
- added category scope
- added category id filter
- updated schemas
=> event filter on category

app/graphql/resolvers/news_items_search.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
- added category id filter
- updated schemas
=> filter news items on category

app/models/data_provider.rb, app/views/accounts/index.html.erb
- der Dataprovider wird nun ausgegeben
- Badge für Rexchte pro Typ wurde übersetzt
- Badge für ob eine Default-Kategorie vorhabden ist wird angezeigt
=> Übersicht der Accountverwaltung verbessert

app/graphql/types/category_type.rb, app/models/data_resources/resource_modules/category.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
=> feat(event filter): add upcoming counts for categories

app/graphql/types/query_type.rb
- added downcased sorting on data provider name when getting
results filtered on category
SVA-32
=> feat(news filter): add sorting on name when filtered on category

app/graphql/resolvers/event_records_search.rb, app/models/data_resources/event_record.rb, app/views/oauth/applications/index.html.erb, config/initializers/devise.rb, config/initializers/doorkeeper.rb
query { eventRecords(order: listDate_DESC, dateRange: ["01.01.2020", "2021-04-12"]) {id, listDate} }
:dateRange is an Array of 2 elements.
- first element is :start_date
- second element is :end_date
Each element should be of format "2020-12-31".
Every other format will be tried to be parsed as well.
Further adjustments:
- Allow Mobile App Users to log in (again)
- Upgrade time to auto logout to 240 minutes
- List Owner in Application index view
=> Filter Events for given date range

Dockerfile, README.md, app/controllers/users/sessions_controller.rb, app/graphql/types/query_type.rb, app/services/resource_service.rb, config/application.rb, config/lograge.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
Was von den Changes, die in Bad Belzig drin sind, aber allgemeiner Natur scheinen, sollten wir in den master-Branch ziehen?
=> chore: update code with diffs from bad belzig release branch

app/controllers/accounts_controller.rb, app/models/data_provider.rb, app/views/accounts/_form.html.erb
- with a new role for lunch we can activate the feature for editing in the cms just when it is needed
=> chore: add role lunch

app/graphql/types/news_item_type.rb, app/models/data_resources/news_item.rb, db/migrate/20210205152344_add_push_notifications_sent_at_to_news_items.rb, db/schema.rb, spec/factories/news_items.rb, spec/models/news_item_spec.rb
=> feat(push): add timestamp to news when push notifications sent

app/graphql/types/query_type.rb
Return JSON Error instead of raising an rails exception if a dataset is not found.
fix #184
=> Better error handling for dataset not found

app/controllers/notification/devices_controller.rb, app/jobs/waste_notification_job.rb, app/models/data_resources/news_item.rb, app/services/push_notification.rb
As a background service to speed up response time in graphql request
=> Send push notifications delayed

app/services/push_notification.rb
Do not break if expo raises an error
=> secure delayjob push retry on expo error

app/models/survey/poll.rb, app/models/survey/question.rb, app/models/survey/response_option.rb
propagate error_message from response_option to question up to poll model
SVA2-5
=> Delete only if no votes exist

app/graphql/types/query_types/survey_poll_type.rb
SVA2-7
necessary for https://github.com/ikuseiGmbH/smart-village-app-cms/pull/70
=> feat(surveys): add missing fields for cms index request

Gemfile, Gemfile.lock, app/controllers/users/sessions_controller.rb, app/graphql/mutations/change_visibility.rb, app/graphql/mutations/destroy_record.rb, app/models/concerns/filter_by_role.rb, app/models/user.rb, app/services/resource_service.rb, app/views/accounts/index.html.erb, app/views/layouts/doorkeeper/admin.html.erb, config/initializers/graphiql.rb, config/routes.rb
- neue Rolle "ReadOnly" hinzugefügt
- in allen Mutation den Zugriff über die Rolle "ReadOnly" verboten
- Leserechte für die RolleReadOnly für alle Resource hinzugefügt
- Setup OAuthToken für graphiQL UI im Session Controller
=> GraphQL UI zum Test der API

Gemfile, Gemfile.lock
mimemagic (0.3.3) has been removed.
=> mimemagic version fix

app/models/survey/comment.rb
=> feat(surveys): allow access of admin contents by editors

app/controllers/accounts_controller.rb, app/views/accounts/_form.html.erb
- add input to data provider form to be able to edit the notice as admin for other accounts as well
SVA-171
=> feat(data provider): add notice inputs to edit at accounts

app/jobs/waste_notification_job.rb
```
Job has failed and won't be retried anymore: Unknown error format: #<Typhoeus::Response:0x00005589e1217120>
/usr/local/bundle/gems/exponent-server-sdk-0.1.0/lib/exponent-server-sdk.rb:127:in `process_response'
/usr/local/bundle/gems/exponent-server-sdk-0.1.0/lib/exponent-server-sdk.rb:63:in `send_messages'
/app/app/jobs/waste_notification_job.rb:23:in `perform'
/usr/local/bundle/gems/delayed_job-4.1.9/lib/delayed/performable_method.rb:26:in `perform'
/usr/local/bundle/gems/delayed_job-4.1.9/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/usr/local/bundle/gems/rollbar-2.21.0/lib/rollbar/plugins/delayed_job/plugin.rb:39:in `block in invoke_job_callback'
```
https://rollbar.com/SmartVillage/SmartVillage-Server/items/178/
SVA-348
=> fix(WasteNotificationJob): add begin rescue like in SendSinglePushNotificationJob

Gemfile, Gemfile.lock, app/controllers/notification/devices_controller.rb, app/controllers/oauth/applications_controller.rb, app/controllers/static_contents_controller.rb, app/views/accounts/index.html.erb, app/views/notification/devices/index.html.erb, app/views/oauth/applications/index.html.erb, app/views/static_contents/index.html.erb
Add pagination to the admin interface for Notification::Devices,
StaticContents, Accounts (aka. Users) & Oauth::Applications
=> [SVA-397] Add pagination

app/graphql/types/query_type.rb, app/graphql/types/query_types/public_json_file_type.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
- updated field type for `content` of `PublicJsonFileType` from `String` to `GraphQL::Types::JSON` to be able to return real jsons
- updated resolver return value for `content` with parsing string to json
- updated graphql schema files
|before|after|
|---|---|
|![Bildschirmfoto 2021-06-16 um 14 36 32](https://user-images.githubusercontent.com/1942953/122221501-9ccac600-ceb1-11eb-8c17-3af77c31e8f9.png)|![Bildschirmfoto 2021-06-16 um 14 36 21](https://user-images.githubusercontent.com/1942953/122221389-845aab80-ceb1-11eb-9d72-b7c6c4f1e92f.png)|
⚠️  **before merge and release we need to ensure, that we check if something is necessary to update in the mobile app**
=> chore(graphql public json file): update content type to json

app/controllers/accounts_controller.rb, app/graphql/mutations/create_or_update_static_content.rb, app/graphql/mutations/create_or_update_survey_poll.rb, app/graphql/mutations/destroy_record.rb, app/graphql/types/mutation_type.rb, app/graphql/types/query_type.rb, app/graphql/types/query_types/public_html_file_type.rb, app/graphql/types/query_types/public_json_file_type.rb, app/models/data_provider.rb, app/models/static_content.rb, app/models/survey/poll.rb, app/views/accounts/_form.html.erb, config/locales/de.yml, public/schema.graphql, public/schema.json, schema.graphql, schema.json, spec/graphql/mutations/create_or_update_static_content_spec.rb
=> Create and edit static contents

Gemfile, Gemfile.lock, app/models/data_resources/resource_modules/content_block.rb, spec/factories/news_items.rb, spec/models/content_block_spec.rb
[SVA-271](https://tpwd.atlassian.net/browse/SVA-271)
=> [SVA-271] Remove emojis from content_blocks

app/services/clean_up_service.rb
=> fix(cleanup service): add early returns if there is no data

app/models/data_resources/resource_modules/content_block.rb, spec/models/content_block_spec.rb
Verified that the new test fails before I created the fix.
=> Fix saving content_block with nil values

app/controllers/users/sessions_controller.rb
[SVA-226](https://tpwd.atlassian.net/browse/SVA-226)
=> Send minio config to CMS when user logs in

app/graphql/types/query_types/category_type.rb, app/models/data_resources/resource_modules/category.rb
=> feat(categories): add tree counts for pois and tours

app/graphql/types/query_types/category_type.rb, app/models/data_resources/resource_modules/category.rb
meanwhile there were new "tree counts" for tours and pois. these were missing in the last PR #315 so i added them with this one.
SVA-475
=> feat(graphql): add location filter for tree counts

app/jobs/waste_notification_job.rb
- added check for presence of `registration_to_check.blank`
- ordered objects and checks more logically
=> fix(waste notification job): secure object accesses

db/migrate/20220704092229_add_index_to_mainserver.rb, db/schema.rb
to get faster responses and save hardware resources
SVA-656
=> Add index to db

app/graphql/types/query_type.rb
=> feat: respect multiple category ids for data providers filter

app/graphql/mutations/create_tour.rb, app/graphql/types/input_types/tour_stop_input.rb, app/models/data_resources/tour.rb, app/models/data_resources/tour_stop.rb, app/models/tour_stop_assignment.rb, app/services/resource_service.rb
- adjusted models to correctly behave on create, update and delete with dependent destroys
SVA-572
=> fix: "updates" of tour stops

app/controllers/accounts_controller.rb, app/graphql/mutations/create_tour.rb, app/models/data_provider.rb, app/views/accounts/_form.html.erb
=> feat: add new account role for tour stops

app/helpers/application_helper.rb
- checkboxes need a hidden field that will be transmitted if nothing is selected to pass that information correctly in order to deselect all options
SVA-660
=> feat: add hidden field to revert default categories

app/graphql/mutations/send_push_notification.rb, app/graphql/types/input_types/push_notification_data_input.rb, app/views/notification/devices/_send_notification.html.erb
SVA-710
|new field|select values|
|---|---|
|![SCR-20221111-hxd](https://user-images.githubusercontent.com/1942953/201335579-de9a3444-52bb-46af-a394-3c8574f2d0ea.png)|![SCR-20221111-hxi](https://user-images.githubusercontent.com/1942953/201335597-36283afb-7815-4a61-8cf7-cc8afe3a3838.png)|
=> feat(push notifications): add data provider id to send to

app/controllers/public/confirm_records_controller.rb, app/controllers/public_controller.rb, app/views/layouts/application.html.erb, app/views/layouts/doorkeeper/admin.html.erb, app/views/layouts/doorkeeper/application.html.erb, app/views/layouts/partials/_head.html.erb, app/views/layouts/public.html.erb, app/views/public/confirm_records/confirm.html.erb, app/views/public/confirm_records/error.html.erb, config/routes.rb
Bestätigungsseite und Action, um einen Eintrag über einen E-Mail Link löschen zu können.
http://localhost:4000/confirmation/destroy/c1ff5c74-7069-4127-9e82-8b6eadd5acf6
leitet nach erfolgreicher Löschung um zu
http://localhost:4000/confirmation/confirmed/c1ff5c74-7069-4127-9e82-8b6eadd5acf6
und im Fehlerfall zu
http://localhost:4000/confirmation/error
SVA-739
=> Public Confirmation and Delete Controller 

app/graphql/mutations/create_generic_item.rb, app/mailers/noticeboard_mailer.rb, app/models/data_resources/generic_item.rb, app/views/mailers/noticeboard/notify_creator.text.erb, spec/mailers/previews/noticeboard_mailer_preview.rb
- preview at: http://localhost:4000/rails/mailers/noticeboard_mailer/notify_creator
SVA-739
=> feat(noticeboard): mail to notify creators

app/mailers/noticeboard_mailer.rb, app/models/data_resources/generic_item.rb, app/models/data_resources/generic_item/message.rb, app/views/mailers/noticeboard/new_message_for_entry.text.erb, spec/mailers/previews/noticeboard_mailer_preview.rb
- preview at: http://localhost:4000/rails/mailers/noticeboard_mailer/new_message_for_entry
SVA-739
=> feat(noticeboard): mail to notify creators on new message for entry

app/controllers/accounts_controller.rb, app/controllers/notification/devices_controller.rb, app/jobs/send_single_push_notification_job.rb, app/jobs/waste_notification_job.rb, app/models/data_provider.rb, app/models/data_resources/news_item.rb, app/services/push_notification.rb, app/views/accounts/_form.html.erb
=> feat(deadlines): add new role

app/controllers/accounts_controller.rb, app/models/data_provider.rb, app/views/accounts/_form.html.erb
=> feat(noticeboard): add new role

app/controllers/notification/push_device_assignments_controller.rb, app/graphql/mutations/schedule_push_notification.rb, app/jobs/send_single_push_notification_job.rb, app/models/notification/device.rb, app/models/notification/push.rb, app/models/notification/push_device_assignment.rb, app/services/push_notification.rb, config/routes.rb, db/migrate/20221202145050_create_notification_push_device_assignments.rb, spec/factories/generic_items.rb, spec/factories/notification_devices.rb, spec/factories/notification_push_device_assignments.rb, spec/jobs/send_single_push_notification_job_spec.rb, spec/models/notification/device_spec.rb, spec/models/notification/push_device_assignment_spec.rb, spec/models/notification/push_spec.rb
=> feat(push notifications): add assignment table, logics and api

app/models/survey/poll.rb
Providing an Array in a where syntax leads to an `or`-sql statement. But in conjunction with an `.not()` the whole statement would be negated instead of being an `or` between all single variants delivered by the array.
`WHERE NOT ((fixed_dates.date_end = NULL OR fixed_dates.date_end IS NULL))` 
vs
`WHERE ((fixed_dates.date_start IS NOT NULL OR fixed_dates.date_start != NULL)`
SVA-834
=> fix: join of `or` and `not` statements

app/controllers/accounts_controller.rb, app/controllers/categories_controller.rb, app/graphql/mutations/create_generic_item.rb, app/graphql/types/input_types/generic_item_input.rb, app/graphql/types/query_types/category_type.rb, app/helpers/application_helper.rb, app/mailers/defect_report_mailer.rb, app/models/data_provider.rb, app/models/data_resources/generic_item.rb, app/models/data_resources/resource_modules/category.rb, app/views/accounts/_form.html.erb, app/views/categories/_form.html.erb, app/views/categories/show.html.erb, app/views/mailers/defect_report/notify_for_category.text.erb, spec/mailers/previews/defect_report_mailer_preview.rb, spec/mailers/previews/noticeboard_mailer_preview.rb
- adjusted category to have optional e-mail addresses for notifications
|index|edit|
|---|---|
|<img width="347" alt="image" src="https://user-images.githubusercontent.com/1942953/207598828-65753fcb-9a54-4e25-a85f-1446a641c3d9.png">|<img width="678" alt="image" src="https://user-images.githubusercontent.com/1942953/207598901-f042d791-c61d-402d-b8a0-a1eeb3c4d834.png">|
- new mail for that e-mail addresses
SVA-738
=> feat(defect repot): add new generic type + mailer

app/controllers/application_controller.rb, config/routes.rb
https://server.int-development.smart-village.app/marcometz.php
=> feat: catch all unknown routes to 404

app/models/data_resources/event_record.rb, app/services/redis_adapter.rb
Caching list_date of EventRecord untill end of day in redis
SVA-933
=> Speed Up EventRecord list_date

Rakefile, bin/start-cron.sh
- include doorkeeper rake tasks
- run cleanup by cronjob
=> Remove old oauth tokens from doorkeeper tables

app/controllers/graphql_controller.rb, app/graphql/resolvers/event_records_search.rb, app/graphql/types/query_type.rb, docker-compose.override.yml
Diese Änderungen beinhalten Verbesserungen an der GraphQL-Controller, dem Event Records Search und dem Query Type. Um die Leistung zu verbessern werden nun dynamisch Includes zum ActiveRecord scope hinzugefügt, wenn diese in der GraphQL Query angefragt werden.
Eine Umgebungsvariable und ein Volumen wurden dem Nginx-Container für die locale Entwicklung mit Docker hinzugefügt.
SVA-933
=> Veränderungen an der GraphQL-Controller, Event Records Search und Query Type

config/locales/devise.de.yml, config/locales/doorkeeper.de.yml
Converted the English content of both Devise and Doorkeeper configuration files into German. This adaptation is crucial for presenting the application interface in German for the target audience.
SVA-285
=> feat: Add German translations for Devise and Doorkeeper

app/graphql/mutations/create_news_item.rb, app/graphql/types/query_types/news_item_type.rb, app/models/data_resources/news_item.rb, db/migrate/20230901090616_add_payload_to_news_items.rb, db/schema.rb, spec/factories/news_items.rb, spec/models/news_item_spec.rb
- added new `payload` field like in all other models
SVA-1145
=> feat(news item): add payload

app/controllers/categories_controller.rb, app/graphql/types/query_types/category_type.rb, app/helpers/application_helper.rb, app/models/data_resources/resource_modules/category.rb, app/views/categories/_form.html.erb, app/views/categories/show.html.erb, db/migrate/20230920135847_add_icon_name_to_categories.rb, db/schema.rb, spec/factories/categories.rb, spec/models/category_spec.rb
- added possibility to save icon names for categories, that can be mapped in the mobile app
- added output on show and index page to see, which category has an icon name
|edit|show|index|GraphQL|
|---|---|---|---|
|<img width="1154" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-mainserver/assets/1942953/5ece324c-27bd-4058-b189-0a348cad69b0">|<img width="348" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-mainserver/assets/1942953/25933a1d-2ad3-4afe-9da1-b3a78ed0c665">|<img width="477" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-mainserver/assets/1942953/fb4728cb-3f7f-4763-a3b1-60168ed38af5">|<img width="237" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-mainserve …
=> feat(categories): add option to set an icon name

Gemfile, Gemfile.lock
to further improve my workflow in VSCode I have installed these gems and among others https://marketplace.visualstudio.com/items?itemName=Shopify.ruby-lsp.
I have also integrated the following pre-commit hook in git: https://gitlab.tpwd.de/-/snippets/16
=> build: add solargraph and rubocop gem

app/services/gtfs_redis_adapter.rb, app/services/public_transportation/import_service.rb
- remove old data on daily imports
- only import future calendar dates
MQGB-48
=> feat: Cleanup old data on import

app/services/public_transportation/import_service.rb
Update geo_location of poi on gtfs import
MQGB-48
=> import geo data

app/models/data_resources/resource_modules/public_transportation/travel_time.rb
this fixes adding not traveling stop_times (but i don't know why)
MQGB-48
=> fix: remove begin/rescue block

app/controllers/users/sessions_controller.rb, app/controllers/users/status_controller.rb, app/models/concerns/filter_by_role.rb, app/models/user.rb, app/services/resource_service.rb, app/views/accounts/_form.html.erb, app/views/accounts/index.html.erb
Can see all resources like an admin, but can only edit his own
SVAK-8
=> feat: New role ExtendedUser

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/controllers/categories_controller.rb, app/graphql/resolvers/categories_search.rb, app/graphql/types/query_types/category_type.rb, app/helpers/application_helper.rb, app/models/data_resources/resource_modules/category.rb, app/views/accounts/_form.html.erb, app/views/categories/_form.html.erb, app/views/categories/show.html.erb, config/locales/data_resource.de.yml, config/locales/data_resource.en.yml
- Categories can be assigned to tags
- Tags for categories are predefined by resource types
- graphQl is extended to export tag_list for CMS
SBB-140
=> feat: Add Tags to Categories

app/controllers/health_check_controller.rb, config/routes.rb, stack.yml
- GET Endpunkt für einen Health-Check eingebaut unter localhost/health-check
- Dieser Endpunkt kann im Docker-Swarm Healthcheck dann verwendet werden.
Manuelle Anpassungen/Korrekturen in den einzelnen stack.yml der Release-Branches sind zu erwarten
=> Zero-Downtime-Deploy

app/graphql/resolvers/categories_search.rb
=> feat(categories): add filter for tag list
