app/controllers/application_controller.rb
*  to make the mobile app communicate with the API endpoint for GraphQL we need to turn off CSRF token validation.
=> Disable CSRF TOKEN validation

Gemfile.lock, app/graphql/mutations/create_tour.rb, app/graphql/types/mutation_type.rb, app/models/geo_location.rb, app/models/tour.rb, doc/tour_mutation_example.graphql, spec/graphql/mutations/create_tour_spec.rb, spec/models/contact_spec.rb, spec/models/point_of_interest_spec.rb, spec/models/region_spec.rb
Add mutation for resource tour
* api needs to provide app with information for tours
* to import these tours from various resources the api graphql server needs a mutation for these resources
* this commit provides this mutation
#44
Add graphql example for mutation to create a tour
Add spec for create_tour mutation
* add spec to to spec  if the resolver creates a valid Tour
#44
Correct failing specs
* models were changed in previous commits so specs needed to be corrected
#44
Correct spec for tour mutation
#44
=> Feature#44/create mutation for resource tour

app/graphql/types/public_html_file_type.rb, app/graphql/types/query_type.rb, public/mobile-app/contents/impress.html, public/mobile-app/contents/privacy.html
- added GraphQL type PublicHtmlFileType with name and content fields
- name is the name of the file and content is the content of the file
- added the query for `public_html_file` with a `name` attribute
- created the pubic folder `public/mobile-app/contents/`
- added two test files in it
- provide contents for a file only if the file is existing and inside of the
specified folder
- this is done per building a whitelist of all html files existing in that folder
and lookup per `include?`
resolves #55
---
| allowed | not allowed |
|---|---|
|![Bildschirmfoto 2019-05-22 um 14 12 22](https://user-images.githubusercontent.com/1942953/58173452-b631c180-7c9b-11e9-8b1a-43f8b023e805.png) | ![Bildschirmfoto 2019-05-22 um 13 52 18](https://user-images.githubusercontent.com/1942953/58173540-ef6a3180-7 …
=> Create GraphQL query for public html files

app/graphql/mutations/create_point_of_interest.rb, app/models/attraction.rb
* whenever a poi is created via a mutation a category will be connected to the new poi
* category is connected by a callback which either finds the category by name in the database or creates it
=> Create Categories for POI

app/graphql/resolvers/news_items_search.rb
* with this commit news_items can be queried with order by published_at (ascending and descending)
=> Add new order possibility to  news_items query

app/graphql/resolvers/event_records_search.rb, app/graphql/resolvers/news_items_search.rb, app/graphql/resolvers/points_of_interest_search.rb, app/graphql/resolvers/tours_search.rb, app/models/event_record.rb, app/models/news_item.rb, app/models/point_of_interest.rb, app/models/tour.rb, app/models/user.rb, config/initializers/doorkeeper.rb, db/migrate/20190621153829_add_role_to_users.rb, db/schema.rb
The goal is for the mobile app to continue reading all data as before, but the individual importer accounts will only be able to read/retrieve their own data.
- adding enum :role in model user. Default is :user
This generates method like „user_role?“ and „admin_role?“
- removes temp method admin?
- replaces new role_method in doorkeeper initializer
- adding a scope : filtered_for_current_user to every queryModel (:tour, :event, :poi, :news_item)
- extending the scopes in graphql queries to use the new model scopes
**!!! As soon as this feature is online, the account for the mobile app has to be adapted online and the role has to be changed to admin (role: 1). Otherwise no data will be visible in the app !!!**
=> Adding role to user for GraphQL

app/graphql/types/contact_type.rb
* graphql type contact had field fax which was Boolean but should have been String
* this lead to fax always return true instead of a fax number
* change fax to type String to fix bug
#97
=> Fix bug in graphql contact type

app/graphql/mutations/create_point_of_interest.rb, app/graphql/types/point_of_interest_type.rb, app/models/point_of_interest.rb, db/seeds.rb, doc/poi_mutation_example.graphql, spec/models/point_of_interest_spec.rb
Im vorherigen PR in dem prices eigentlich umbenannt worden ist, haben noch einige Stellen gefhlt  wo auch noch prices steht. Diese stellen sind nach merge dieses Pr auch in price_informations geändert
=> Rename prices to price_informations where necessary

app/graphql/mutations/destroy_record.rb
* add argument external_id to make deletion of a record by external_id possible
* this way maz can send a delete request to maz converter with an external_id and destroy_record mutation can find a record to be destroyed by external_id
PR connected to the following other PRs:
https://github.com/ikuseiGmbH/smart-village-app-converter-json2graphql/pull/3
https://github.com/ikuseiGmbH/smart-village-app-maz-converter/pull/2
It needs to be reviewed together with them.
=> Add feature to destroy_record mutation

app/graphql/resolvers/points_of_interest_search.rb, app/graphql/resolvers/tours_search.rb
* add category option  and method to search resolver objects to be able to query for pois or tours which belong to a certain category
closes #113
=> Add category filter to tour and point of interest

app/graphql/types/category_type.rb, app/models/category.rb
- we need to group by categories for points of interest or tours in the mobile app
- we do not want to render empty categories (without any counts)
- added count fields for both to graphql CategoryType
- added methods for that fields to model Category
updates #116
=> Add fields for model counts to CategoryType

app/graphql/types/date_input.rb, spec/factories/fixed_dates.rb
Is it necessary to write a capital D in `time_Description`?
If not, we can merge this PR for an all lowercase argument `time_description`.
=> Change time_Description to time_description

app/graphql/mutations/create_news_item.rb, app/graphql/types/news_item_type.rb, app/models/data_resources/news_item.rb, db/migrate/20200511112404_change_externalid_to_string_for_newsitem.rb, db/schema.rb, spec/factories/news_items.rb, spec/models/news_item_spec.rb
Über die RSS Feed ist nun manchmal die externalD identisch zur Überschrift der News und damit ein Text und nicht zwingend immer eine Zahl
=> Changinge external id to string

app/controllers/users/sessions_controller.rb
in Doorkeeper 5.1.1. `to_json` has been restricted for an oauth_application.
We extend the response here as we need them in our external services like cms or json importer
=> Fix for Doorkeeper update 5.1.1

app/controllers/static_contents_controller.rb, app/models/static_content.rb, app/views/static_contents/index.html.erb
- added scope on `data_type` for `StaticContent` to
be able to filter for specific records
- added usage of scope in `#index` for `StaticContentsController`
if a url param is present
- added buttons in the index template to trigger certain filter
- included a helper method to determine the css class for
buttons depending on url params and a given type
=> feat(static contents): add scope for data type

app/models/static_content.rb, app/views/app_user_contents/_form.html.erb, app/views/app_user_contents/show.html.erb, app/views/static_contents/_form.html.erb, app/views/static_contents/show.html.erb, spec/models/static_content_spec.rb
- updated setup for JSONEditor
- set correct typed fallbacks for empty contents
- updated the editor for app user contents as well
- added model validations for `StaticContent`
- a `name` must be unique without regarding the case
Fixes #142
=> fix(content editor): fix creation of JSON static contents

app/graphql/resolvers/event_records_search.rb, app/models/data_resources/event_record.rb
- added a new scope to filter event records
- return only upcoming events
- a current user can be applied to pre filter records
with using the existing  scope `filtered_for_current_user`
- updated the graphql resolver for event records to
use the new scope, whichs implies the previous one
Resolves #145
=> refactor: scope event records to upcoming ones

.gitlab-ci.yml
refactor: add specific branch for gitlab-ci build
- add only option with the branch, that is set for the other
stages
refactor(gitlab ci): update branch name in only options
- set to a branch, that does not exist, because master should
not trigger anything
Resolves #147
=> refactor: add specific branch for gitlab-ci build

app/graphql/resolvers/event_records_search.rb
- sorting event records by list_date returns an array, so `offset` and
`limit` cannot be used
- `offset` can be achieved for arrays with `drop`
- thx to: https://stackoverflow.com/a/29511939
- `limit` is equivalent to `first`
- the order of options is relevant for the called chain of methods
- knowing this, `skip` needs to be the first method that is called
to have correct results
=> fix: update resolver methods to succeed when combined with arrays

app/controllers/application_controller.rb, config/routes.rb
- create a simple head-only route to return a 204 status
with no content
- this can be used by the app to check, if the mainserver is up
and reachable
- currently a default `https://clients3.google.com/generate_204`
is used, which does not help us to check for the main server
- on the other hand, we do not want to depend on google for
that case
=> feat: add alive check endpoint for the mobile app

app/graphql/resolvers/news_items_search.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
- added dataProvider option and method to search resolver objects to be
able to query for news items, which belong to a certain data provider
- updated schemas per `rails graphql:schema:dump`
- copied the two schema files from public/ to /, because they are
also there for some very unclear but necessary(?) reason
SVA-31
=> feat(news filter): add option to filter news on data providers

app/graphql/types/query_type.rb, app/models/data_provider.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
- added query for data providers, which have news items in the database, which
can be used as a filter list in the app
- the sql query gets only the data providers per `:includes`, which are connected
in the news items table per `data_provider_id` (news_item belongs_to data_provider)
- updated schemas per `rails graphql:schema:dump`
- copied the two schema files from public/ to /, because they are
also there for some very unclear but necessary(?) reason
SVA-31
=> feat(news filter): add query for data providers of news items

app/controllers/accounts_controller.rb, app/models/data_provider.rb, app/models/data_resources/point_of_interest.rb, app/models/data_resources/tour.rb, app/views/accounts/_form.html.erb, app/views/accounts/index.html.erb, config/locales/doorkeeper.en.yml, config/routes.rb, lib/tasks/batch_defaults.rake
- UI erweitert um eine BatchAction für einen DatenTyp zu starten
- RakeTask angelegt, der die eigentliche Action ausführt
- Datenmodel von DataProvider erweitert, sodass seine data_resources direkt angesprochen werden können
=> Batch action update default categories

app/graphql/resolvers/event_records_search.rb, app/graphql/resolvers/news_items_search.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
- match the category id type to have the same across all queries
- updated schemas per `rails graphql:schema:dump`
- copied the two schema files from public/ to /, because they are
also there for some very unclear but necessary(?) reason
SVA-32
=> feat(categories): match type of category id

app/graphql/resolvers/event_records_search.rb
- we do not know if we can call `with_category` on the scope, because the
scope can be an array through other actions
- therefore we need to add a fallback action to filter the array,
like for `skip` and `limit`
SVA-58
=> fix(event filter): add fallback for category filter if scope is an array

app/graphql/resolvers/event_records_search.rb
- somehow it helps to put `:categoryId` in first place, as it will
be called prior to the others
- BUT `:order` will be called even before `:categoryId`, no matter that
it is listed in last position of these options
- why?
SVA-58
=> feat(event filter): change order of calling options

app/controllers/notification/devices_controller.rb
if somehow multiple devices exist with the same token, all of them are now destroyed.
=> Cleanup all devices

app/controllers/notification/devices_controller.rb, app/models/notification/device.rb, db/migrate/20201127072145_add_index_to_notification_devices.rb, db/schema.rb
validates_uniqueness_of ist unter Umständen zu langsam:
https://stackoverflow.com/questions/23187037/rails-whats-difference-in-unique-index-and-validates-uniqueness-of
Ein unique Index auf das Feld token löst dieses Problem datenbankseitig und wirft einen Fehler zurück, falls Ein Eintrag über mehere Worker hinweg parallel versucht wird anzulegen.
Der Fehler wird nun im Controller abgefangen und ebenso als Status 422 zurückgeliefert wie es validates_uniqueness_of auch tut.
=> Absicherung der Geräteregistrierung

app/controllers/accounts_controller.rb, app/graphql/mutations/create_news_item.rb, app/graphql/types/category_input.rb, app/models/data_provider.rb, app/models/data_resources/event_record.rb, app/models/data_resources/news_item.rb, app/views/accounts/_form.html.erb, app/views/layouts/doorkeeper/admin.html.erb
Argument 'categories' added with a new InputType CategoryInput as an array.
Each category name will be created and added to the news_item object
=> Add multiple categories per graphql

Gemfile, Gemfile.lock, app/controllers/accounts_controller.rb, app/graphql/resolvers/event_records_search.rb, app/graphql/resolvers/news_items_search.rb, app/graphql/resolvers/points_of_interest_search.rb, app/graphql/resolvers/tours_search.rb, app/graphql/types/data_provider_input.rb, app/graphql/types/data_provider_type.rb, app/models/data_provider.rb, app/models/data_resources/event_record.rb, app/views/accounts/_form.html.erb, db/migrate/20201201122547_add_datatype_to_data_providers.rb, db/schema.rb
Ziel ist es, dass bei einem POI eines Datenlieferanten alle News und Events des gleichen Datenlieferanten dargestellt werden können.
Hierzu gibt es nun neue Filteroptionen in allen DataResources nach dem Namen und der ID des DataProviders (dataProvider, dataProviderId)
Die Information, ob eine Standort verknüpfte Daten anzeigen soll, hängt ebenfalls am DataProvider: data_type
Der Datentyp ist entweder 'general_importer' oder 'business_account', wobei der BusinessAccount derjenige ist, der eine Repräsentation zu einer Firma darstellen soll, bei der dann News und Events mit dargestellt werden sollen.
=> Verknüpfung der DataResources untereinander

app/graphql/mutations/change_visibility.rb, app/graphql/types/change_visibility_type.rb, app/graphql/types/event_record_type.rb, app/graphql/types/mutation_type.rb, app/graphql/types/news_item_type.rb, app/graphql/types/point_of_interest_type.rb, app/graphql/types/tour_type.rb, app/models/concerns/filter_by_role.rb, app/models/data_resources/event_record.rb, app/models/data_resources/news_item.rb, app/models/data_resources/point_of_interest.rb, app/models/data_resources/tour.rb, app/models/user.rb, app/services/resource_service.rb, app/views/accounts/_form.html.erb, app/views/accounts/index.html.erb, app/views/layouts/doorkeeper/admin.html.erb, db/migrate/20201127102350_add_active_to_dataresources.rb, db/schema.rb
Compared to destroyRecord, ther is a new mutaion to update the visibility aof an dataresource
`mutation { changeVisibility (id: 456, recordType: "NewsItem", visible: false){id, status, statusCode} }
Extend GraphQl to get status of  visibility for all 4 dataresources
Backend extended for additional roles and added documentation:
=> Add Mutation to change Visibility

db/migrate/20201203145226_fix_precision_in_geo_locations.rb, db/schema.rb
Die vorhandenen GeoDaten waren als Float in der Datenbank codiert, sodass nach 4 Stellen hinter dem Komma gerundet wurde.
Der Wechsel zu einem Double erhöht die Anzahl der Stellen hinter dem Komma und damit die Genauigkeit der GeoCoordinaten.
Erstaunlicherweise sind die genaueren Werte auch bereits in der DB gespeichert.
=> Genauigkeit der GeoDaten verbessert

app/graphql/resolvers/event_records_search.rb, app/graphql/resolvers/news_items_search.rb, app/graphql/resolvers/points_of_interest_search.rb, app/graphql/resolvers/tours_search.rb
Liste an IDs zum Filtern kann nun an SearchQuerys mitgegeben werden.
query { newsItems (ids: [434,429]){id, author …
Richtige Syntax hier gefunden: https://github.com/rmosolgo/graphql-ruby/issues/1895
=> Filter Newsitem for given ID

app/services/resource_service.rb
Die zuvor aktualisierten Parameter zum Erstellen von Datensätzen bei eingeschränkten Accounts wurden nicht verwendet.
=> Hotfix: aktualisierte Params auch verwenden

app/graphql/mutations/create_event_record.rb, app/graphql/mutations/create_point_of_interest.rb, app/graphql/mutations/create_tour.rb, app/models/data_resources/attraction.rb, app/models/data_resources/event_record.rb, app/models/data_resources/news_item.rb
- added possibility to perform mutations for multiple categories for event records, points of interest, tours
- copied logics from news items
- made callback methods private
Closes #181
=> feat: allow multiple categories for mutations

app/models/data_resources/event_record.rb, app/services/resource_service.rb
- Every resourcemodel can have a method :compareable_attributes
which returns a hash of attributes to determine changes
- Fallback will be the currently compared attributes
- for the model EventRecord :compareable_attributes is defined
to also include the attributes of the first date fields
=> Compare of changed attributes per resource

app/controllers/accounts_controller.rb, app/models/data_provider.rb, app/views/accounts/_form.html.erb
- added more accessors to `roles` store of `DataProvider` to be able to save and make more data types depending on the roles
=> feat(account): add roles for jobs, offers and construction sites

app/graphql/resolvers/waste_location_search.rb, app/graphql/types/input_types/waste_location_type_input.rb, app/graphql/types/query_type.rb, app/graphql/types/query_types/waste_location_type_type.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
- there were some missing class nestings after refactoring, which will not break the rails server to run, but can be found out when building the schemas with `rake graphql:schema:dump`
- following error came up for example:
- NameError: uninitialized constant Types::QueryTypes::WasteLocationTypeType::AddressType
- NameError: uninitialized constant Types::AddressType
=> fix: correct graphql types

app/views/static_contents/_form.html.erb, app/views/static_contents/show.html.erb
- added json parsing to check if content is valid
- added checks for triggering json editor javascript only if the container with the id is present
- added fallback rendering if json is not valid to show content anyways in show view
- added fallback text area if json is not valid to be able to edit the content anyways in edit view
|render content if error with json|edit text area to edit json with error|show editor for fixed json|
|----|----|----|
|![Bildschirmfoto 2021-03-29 um 19 13 09](https://user-images.githubusercontent.com/1942953/112874776-a10df100-90c3-11eb-85ce-045d18a99f53.png)|![Bildschirmfoto 2021-03-29 um 19 13 14](https://user-images.githubusercontent.com/1942953/112874794-a703d200-90c3-11eb-9c62-2f350b363683.png)|![Bildschirmfoto 2021-03-29 um 19 13 …
=> feat(static contents): handle json errors

app/controllers/notification/devices_controller.rb, app/services/redis_adapter.rb
Rename method to better represent storage as a list.
Extend time to life to 96 hours in Redis.
=> Extend store time to 96 hours

app/graphql/types/query_types/category_type.rb, app/models/data_resources/attraction.rb, app/models/data_resources/event_record.rb, app/models/data_resources/generic_item.rb, app/models/data_resources/news_item.rb, app/models/data_resources/resource_modules/category.rb
Scope :visible hinzugefügt zu:
- Attraction (Tour/POI)
- EventRecord
- NewsItem
- GenericItem
Alle DataResource Counter zählen nun nur noch die sichtbaren Elemente.
Zusätzlich wurde der Vollständigkeit halber ein Counter für GenericItem hinzugefügt
=> Visible-Scope zu relevanten DatatResources hinzugefügt und im Category Counter verwendet

app/graphql/mutations/destroy_record.rb, app/models/survey/poll.rb, app/models/survey/question.rb, app/models/survey/response_option.rb, spec/factories/survey.rb, spec/models/survey_spec.rb
c4eb661 feat(surveys): allow deletion of `Survey::Poll`s
61827ae feat(surveys): add return case if records cannot be deleted because of errors
ed89475 feat(surveys): add :destroy for dependencies of `Survey::Poll`
1458bd3 feat(surveys): remove before_destroy checking votes
SVA2-6
- everything should be destroyed if a survey deletion is triggered
> Wenn ich eine Umfrage lösche, löschen sich alle zugehörigen Antworten, Stimmen und Kommentare automatisch mit
- on the other hand, the logic did not work properly while testing the `before_destroy` check
=> feat(surveys): allow deletion of `Survey::Poll`s

app/services/resource_service.rb
If a Record is marked as "not visible", the duplication recognition valid and would have generated a new record.
Last seen as TMB-Imports of "Apotheken"
=> Skip recreation of similar records if invisible

app/controllers/users/sessions_controller.rb, app/services/api_request_service.rb
Der Login schlägt fehl wenn der Account keine OAuth-Application besitzt.
Diese wird normalerweise beim anlegen des Accounts erzeugt, aber wenn diese Manuell gelöscht wird oder zu Test/Dev-Zwecken nicht vorhanden ist, schlägt hier der Login fehl.
Daher wird nun vorab geprüft, ob es mindestens eine OAuth-App für den anzumeldenden User gibt.
=> Admin Account ohne OAuto Application

app/graphql/mutations/change_visibility.rb, app/graphql/mutations/comment_survey.rb, app/graphql/mutations/vote_for_survey.rb, app/graphql/types/mutation_type.rb, app/graphql/types/query_type.rb, app/graphql/types/query_types/survey_comment.rb, app/graphql/types/query_types/survey_poll_type.rb, app/models/survey/comment.rb, app/models/survey/poll.rb, db/migrate/20210702072005_create_survey_comments.rb, db/schema.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
Models erweitert und API  erstellt um:
- Kommentar zum erstellen für die App
- Kommentare an eienr Umfrage laden
- Kommentare einzeln für eine bestimmte Umfrage laden
- Sichtbarkeit eines Kommentars ändern
Rollen und Rechte werden weiterhin wie bei den anderen Resourcen berücksichtigt. Die Rolle der Umfrage ist hierbei maßgeblich für die Rolle der zugehörigen Kommentare
SVA2-22
---
```
query { surveys (){ id questionTitle date{dateEnd} comments:surveyComments{message visible} responseOptions{title votesCount}} }
mutation { changeVisibility (id: 1, recordType: "Survey::Comment", visible: true){id, status, statusCode} }
query { surveyComments { id surveyPollId message } }
query { surveyComments (surveyId: 1){ id surveyPollId message } }
mutation { commentSurvey (surveyId: 1, message: "Dies …
```
=> Survey Comments

app/jobs/send_single_push_notification_job.rb, app/services/push_notification.rb, config/initializers/delayed_job_config.rb
- a delayed job task can only be executed one time
- max runtime is extendet to 8 hours
- the backgroundjob of sending a push to all devises will now create
an additional background job to send each single push notification
=> A push article to 4000 devices will now lead to 4000 delayed_job entries,
wich will be handled one by one.
=> Securing push notifications

app/models/data_resources/resource_modules/fixed_date.rb, db/migrate/20210830070503_change_time_description_to_text.rb, db/schema.rb, spec/factories/fixed_dates.rb, spec/models/fixed_date_spec.rb
added migration to change time_description from string to text to prevent import errors
by delivering long descriptions.
https://rollbar.com/SmartVillage/SmartVillage-Server/items/157
SVA-263
=> change time_description to text

app/models/data_resources/attraction.rb, app/models/data_resources/point_of_interest.rb, app/models/data_resources/tour.rb, db/migrate/20210830095926_change_mobile_description_to_text.rb, db/schema.rb, spec/factories/tours.rb, spec/models/point_of_interest_spec.rb, spec/models/tour_spec.rb
added migration to change mobile_description from string to text to prevent import errors
by delivering long descriptions for model attractions.
SVA-263
=> change mobile_description to text

app/controllers/data_provider_controller.rb, app/graphql/types/input_types/data_provider_input.rb, app/graphql/types/query_types/data_provider_type.rb, app/models/data_provider.rb, app/models/survey/comment.rb, app/models/survey/poll.rb, app/views/data_provider/edit.html.erb, db/migrate/20211109150013_add_notice_to_data_providers.rb, db/schema.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json, spec/factories/data_providers.rb, spec/models/data_provider_spec.rb
- added `notice` to be able to set some additional text for data provider information, that can be displayed in the mobile app
- html is possible
- updated graphql types and schema
- updated annotations
- added input to data provider form to be able to edit the notice
SVA-171
|data in db|data per grapqhl|edit notice|
|---|---|---|
|<img width="364" alt="Bildschirmfoto 2021-11-09 um 16 12 19" src="https://user-images.githubusercontent.com/1942953/140950667-f3790cac-be9b-4f3e-ad9b-151b248dfbf6.png">|<img width="657" alt="Bildschirmfoto 2021-11-09 um 16 12 29" src="https://user-images.githubusercontent.com/1942953/140950697-45f13804-d2a8-4660-98fb-86f56d549e54.png">|![Bildschirmfoto 2021-11-09 um 16 20 00](https://user-images.githubusercontent.com/1942953/140952278-1e38a8fe-e0e7-444d-aebe-786 …
=> feat(data provider): add notice field

app/graphql/resolvers/points_of_interest_search.rb, app/graphql/resolvers/tours_search.rb, app/models/data_resources/attraction.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
- added scope `with_category` and query option to points of interest and tours to attractions like it is already existing for news, event records and generic items
- updated graphql schema
SVA-353
---
you can query now like
```
{
"limit": 100000,
"order": "updatedAt_DESC",
"categoryId": 3
}
```
the existing ability with `"category": "Schlösser und Parks"` is still available for pints of interest and tours.
=> feat: add ability to query POIs and Tours with `categoryId`

app/graphql/loaders/directus_loader.rb
- added `StandardError` to rescue, because:
> Style/RescueStandardError: Avoid rescuing without specifying an error class.
- updated comments
SVA-219
=> refactor(DirectusLoader): restructure and add standard error

app/controllers/accounts_controller.rb, app/controllers/concerns/sortable_controller.rb, app/controllers/notification/devices_controller.rb, app/controllers/static_contents_controller.rb, app/models/concerns/sortable.rb, app/models/notification/device.rb, app/models/static_content.rb, app/models/user.rb, app/views/accounts/index.html.erb, app/views/application/_sort_icon.html.erb, app/views/notification/devices/index.html.erb, app/views/static_contents/index.html.erb, spec/models/concerns/sortable_spec.rb, spec/models/static_content_spec.rb
~~One model "concern" that is actually just a module with some meta-programming magic, because I wanted to use `include` it with parameters to instantly say which fields can be sorted.~~
We now use a "real" `ActiveSupport::Concern` here for simplicity and include a
`sortable_on :field1, :field2`
syntax, which looks more rails-ish.
One controller concern to use the sortable features in that controller and add the `helper_method` for the view
=> Refactor sorting in to concerns

app/assets/stylesheets/buttons.scss, app/controllers/accounts_controller.rb, app/controllers/notification/devices_controller.rb, app/controllers/static_contents_controller.rb, app/models/concerns/searchable.rb, app/models/notification/device.rb, app/models/static_content.rb, app/models/user.rb, app/views/accounts/index.html.erb, app/views/application/_search_form.html.erb, app/views/notification/devices/index.html.erb, app/views/static_contents/index.html.erb, config/locales/en.yml, spec/models/concerns/searchable_spec.rb
Provide search functionality in the admin interface.
Originally I wanted to use a gem for this, but I didn't find one that matched my (super simple) needs:
- [ransack](https://github.com/activerecord-hackery/ransack) is far too complex for what we want to do
- [minidusen](https://github.com/makandra/minidusen) seems to do what we want, but the API is ugly
- [textacular](https://github.com/textacular/textacular) looked perfect, but it only supports postgres
So, once again, I wrote my own concern, `Searchable`. It's awfully simple and essentially only adds syntactic sugar for `'WHERE column LIKE %str%'`. Could have just written the SQL to the controllers tbh, but I only realised halfway through that what I want to do is THIS simple.
And also, I don't like sql inside of controllers. …
=> [SVA-398] Search admin interface

app/controllers/accounts_controller.rb
- added missing relation to kaminari so visiting the index page resulted in an error with `undefined method 'total_pages'`
SVA-397
=> hotfix: pagination for accounts

app/graphql/resolvers/event_records_search.rb, app/graphql/resolvers/generic_item_search.rb, app/graphql/resolvers/news_items_search.rb, app/graphql/resolvers/points_of_interest_search.rb, app/graphql/resolvers/tours_search.rb, app/graphql/types/query_type.rb, app/models/data_resources/attraction.rb, app/models/data_resources/event_record.rb, app/models/data_resources/generic_item.rb, app/models/data_resources/news_item.rb
Added possibility to filter `DataProvider` in `newsItemDataProviders` query with `exclude` parameter
SVA-308
**New query example:**
```graphql
query NewsItems($ids: [ID!]) {
newsItems(excludeDataProviderIds: $ids) {
id
contentBlocks {
title
}
dataProvider {
id
}
}
}
```
Example variables:
```graphql
{
"ids": [
1,
3,
5
]
}
```
=> [SVA-308] Add exclude filter for newsItemsDataProviders query

app/graphql/mutations/create_or_update_static_content.rb, app/graphql/mutations/create_or_update_survey_poll.rb, app/models/static_content.rb, app/models/survey/poll.rb
- added `filtered_for_current_user` when creating or updating surveys and static contents to respect roles entirely
- added `compact` on retrieving `survey_poll_ids` to avoid crashes when `dateable` map returns an array with `nil`s
- updated scope for static contents to restrict abilities just for admins and editors
SVA-388
=> fix(roles): add missing filter scope for surveys and static contents

app/graphql/types/query_type.rb, app/models/static_content.rb, db/migrate/20220117182809_add_version_to_static_contents.rb, db/schema.rb, public/schema.graphql, public/schema.json, schema.graphql, schema.json
- added possibility to query for certain version numbers to get more feature specific static contents
- adjusted uniqueness validation to be able to have several static contents with the same name if there are different versions
- updated graphql schema
SVA-150
---
json:
```
query PublicJsonFile($name: String!, $version: String) {
publicJsonFile(name: $name, version: $version) {
content
}
}
// variables with optional version
{
"name": "wasteTypes",
"version": "1.1.1"
}
```
returns `wasteTypes-1.1.1` or lower existing version like `wasteTypes-1.0.0` or without version `wasteTypes` if existing
---
html:
```
query PublicHtmlFile($name: String!, $version: String) {
publicHtmlFile(name: $name, version: $version) {
content
}
}
// variables with optional version
{
"name": "impressum",
"version": …
```
=> feat(static contents): add versioned returns

app/views/static_contents/_form.html.erb, app/views/static_contents/index.html.erb, app/views/static_contents/show.html.erb
- added abilities to see and edit version numbers for static contents
SVA-150
---
|index|show|edit|
|---|---|---|
|![Bildschirmfoto 2022-02-03 um 12 29 55](https://user-images.githubusercontent.com/1942953/152335162-ce486b33-6eaf-4179-8f50-32ed0999630c.png)|![Bildschirmfoto 2022-02-03 um 12 30 09](https://user-images.githubusercontent.com/1942953/152335181-17631518-5766-4e19-a6aa-6f30b387c110.png)|![Bildschirmfoto 2022-02-03 um 12 29 17](https://user-images.githubusercontent.com/1942953/152335203-d07500dc-2485-4219-9fd1-caa32f0ad3cc.png)|
=> feat(static contents): index, show, edit versions

app/graphql/mutations/create_or_update_static_content.rb, app/graphql/types/query_types/public_html_file_type.rb, app/graphql/types/query_types/public_json_file_type.rb, app/models/static_content.rb, app/views/static_contents/_static_content.json.jbuilder, public/schema.graphql, public/schema.json, schema.graphql, schema.json, spec/factories/static_contents.rb, spec/graphql/mutations/create_or_update_static_content_spec.rb, spec/models/static_content_spec.rb
- took `version` into account for static contents
- updated graphql schema
SVA-315
=> feat: create and edit versioned static content

app/graphql/types/query_types/category_type.rb
- sorted fields for better overview
- added missing field for `generic_items` as for the other
fields with `count`s
- added fields for ancestry methods `parent` and `children`
to be able to traverse through categories per graphql
SVA-28
---
=> feat(category): respect ancestry in graphql queries

app/graphql/resolvers/points_of_interest_search.rb, app/graphql/resolvers/tours_search.rb
- added option to query for multiple category ids
- updated graphql schema
SVA-475
---
this makes it possible to pass `"categoryIds": [3,4]`. `"categoryIds": 3` also works with the plural key, but the singular `"categoryId"` key is kept for backwards compatibility, as that feature was introduced in past november.
=> feat: add ability to query POIs and Tours with `categoryIds`

app/controllers/static_contents_controller.rb, app/models/static_content.rb
- added `:version` in controller to permit its value
- added `enforce_nil_for_empty_version` callback
to ensure `nil` instead of empty strings after editing
in order to satisfy validation scope for `:version`
- until now `nil` and empty string were not handled as
same value thus the validation failed
=> fix(static content): save version

app/models/data_resources/waste/device_registration.rb
- `notify_at_time` is used to set the runner time for delayed jobs to send notifications
- therefore we need to adjust the time zone because we save UTC in the database
SVA-467
=> fix(waste calendar): adjust time zone for delayed jobs

app/controllers/categories_controller.rb
- if not logged in the /categories route returned a 500, because admin stuff was not checked
- copied actions and method from `AppUserContentsController`
=> fix: add missing auth before action to /categories

app/models/static_content.rb
- changed check in `enforce_nil_for_empty_version` from
`.empty?` to `.blank?` to catch cases, where `version` is
already `nil`
---
fixes Rollbar `#224 NoMethodError: undefined method 'empty?' for nil:NilClass`
=> fix(static content): nil version

app/graphql/types/query_type.rb
- this adds the old code before the change in #226 for requests without app versions, that new versions are always sending
=> fix(static contents): add fallback format for old app versions

app/graphql/types/query_types/category_type.rb, app/models/data_resources/resource_modules/category.rb, app/models/static_content.rb
graphql Calls umgebaut:
```
query { categories{
name
genericItemsCount(location: "Hamburg")
genericItems(location: "Berlin"){title}
pointsOfInterestCount
pointsOfInterest{name}
eventRecordsCount
toursCount
tours{name}
upcomingEventRecordsCount
upcomingEventRecords{title}
}
}
```
SVA-475
=> Field Definition mit optionalem `Location` Argument

app/services/waste_notification.rb
- updated `date_time_to_run` to convert times, that are given as winter
because of `time` database field, which serves on first of january,
to the local time zone to correct it to summertime if it is summer
SVA-467
---
given 10:06 in summer to get a push.
old result, which is 09:06 utc and 11:06 in summer:
```
DateTime.parse("#{check_date} #{registration_to_check.notify_at_time}")
=> Wed, 04 May 2022 09:06:00 +0000
```
new result, which is 08:06 utc and 10:06 in summer:
```
Time.zone.parse("#{check_date} #{registration_to_check.notify_at.to_s(:time)}")
=> Wed, 04 May 2022 10:06:00 CEST +02:00
```
=> fix(waste notifications): convert time to correct time zone

db/migrate/20220511120447_larger_unique_id_in_external_references.rb
current field in db is to short and results to import errors
=> fix: larger db field for unique_id in external_references

app/services/category_service.rb, bin/start-cron.sh, lib/tasks/batch_defaults.rake
Einmal am Tag wird nun ein Job gestartet, der für alle DataProvidern und alle DataResourceTypes
die Defaultwerte der Kategorien überprüft und fehlende setzt.
SVA-528
=> Absicherung der Default Kategorien

app/services/category_service.rb, db/migrate/20220525095902_cleanup_multiple_category_assignments.rb
- fixing compare string with int in Line 22
`category_ids_to_add = default_category_ids - data_element.category_ids`
["1"] - [1] => ["1"]
- adding migration to cleanup once multiple category assignments 
SVA-610
=> Distinct category assignment by batch action

app/services/waste_notification.rb
Der WasteNotification Job wird einmal am Tag per Cronjob gestartet.
Sollte der Cronjob fehlerhaft sein und neustarten oder manuell gestartet werden, kann es passieren, dass der gleiche WasteNotificationJob mehrmals in die Warteschlange in DelajedJob geschrieben wird.
Diese Erweiterung prüft vorab, ob es bereits einen WasteNotificationJobs mit den identischen Parameter Argumenten gibt bevor er in die Warteschlange gelegt wird.
Hierbei ist egal wann die Benachrichtigung erfolgen soll. Lediglich die Userregistrierung und der Abfalltyp ist für die Prüfung relevant.
SVA-620
=> Prüfung auf  bereits existierende WasteNotificationJobs

Gemfile.lock, app/graphql/resolvers/news_items_search.rb
Updated ffi gem to make it work with m1 mac and added an news search option to query for multiple categories per id, like we already implemented for attractions.
SVA-660
=> feat(news): add option to query multiple category ids

app/graphql/mutations/create_waste_pick_up_time.rb
Allow an api importer to run multiple times without resulting in duplicate waste pickup times. Only create a pickuptime for an waste_location_type only once, if the params are identical.
=> Resending the Query now returns always the same ID instead of a new one
SVA-803
=> Prevent duplicate entries of pickuptimes

app/controllers/notification/wastes_controller.rb
- remove :street, :city and :zip from search params if blank
- generate full_address without empty strings if search params parts are blank
SVA-803
=> fix(waste_exporter) Remove empty param parts for address search in waste exporter

app/controllers/notification/devices_controller.rb, app/jobs/send_single_push_notification_job.rb, app/jobs/waste_notification_job.rb, app/models/data_resources/news_item.rb, app/services/push_notification.rb
- added cleanup if push notification was tried to sent to unregistered device
- fixed check for `notification_device` in params for `set_notification_device` because navigating in the backend to a device failed
- refactored waste notifications sending of pushs to reduce repetitions
- moved `if Rails.env.production?` entirely in `send_notification` instead of having it at several places, because we do not want to process push notifications in development mode (or others)
SVA-816
=> feat: cleanup notification devices

app/graphql/mutations/schedule_push_notification.rb, app/graphql/types/mutation_type.rb, app/graphql/types/query_types/generic_item_type.rb, app/graphql/types/query_types/push_notification_data_type.rb, app/graphql/types/query_types/push_notification_type.rb, app/models/data_resources/generic_item.rb, app/models/notification/push.rb, app/services/push_notification.rb, bin/start-cron.sh, db/migrate/20221125161012_create_notification_pushes.rb, db/migrate/20221128112410_change_is_recurring_to_integer.rb, db/migrate/20221128115505_add_content_fields_for_notification_pushes.rb, spec/factories/generic_items.rb, spec/factories/notification_pushes.rb, spec/graphql/mutations/schedule_push_notification_spec.rb, spec/models/notification/push_spec.rb
This PR adds a new model that can store timings several configured timings for push notifications and adds a relation for generic items. This also extends with a mutation to schedule push notifications, which will be used by the CMS.
A last step is a new job, that checks for timings each day to delay push notifications that should take place once at a specific date and time or recurring on specific weekdays.
SVA-710
=> feat(push notifications): create model for storing timings, connect to generic items and create mutation to schedule

app/models/data_resources/resource_modules/media_content.rb
Mir ist unklar warum, aber ein "attachment.attach" in Zeile 30 führt (neuerdings) zu einem save mit dem ausführen aller Callbacks. Dadurch entsteht eine Endlosschleife die nicht durchbrochen wird, da die Abbruchbedinnung erst in Zeile 35 zustandekommen würde.
Durch den Wechsel zu after_create statt after_save wird der Callback nun garantiert nur noch einmal gestartet.
eventueller Nachteil: Wenn nachträglich die URL eines MediaContents nun verändert wird wieder zu einer neuen Source-URL würde diese nicht erneut in das eigene MinIO importiert werden. Es bleibt dann bei der neuen Source-URL.
=> fix: URL Umschreibung nur noch nach create

app/models/data_resources/event_record.rb
Use sql to get events where date_start or date_end is in the future instead of calling the method :list_date on each event_record
SVA-819
=> Speed up events query

app/controllers/media_contents_controller.rb, app/mailers/defect_report_mailer.rb, app/models/data_resources/resource_modules/media_content.rb, app/views/mailers/defect_report/notify_for_category.text.erb, config/routes.rb, spec/mailers/previews/defect_report_mailer_preview.rb
- added routed to create media content uploads with ``` media_content[attachment] = "/example/file.png" media_content[content_type] = "image" ``` as `POST` to: `/media_contents`
- returns the media content and the service url as json - copied `service_url` from `convert_source_url_to_external_storage`
SVA-738
=> feat(defect report): add media content upload

docker-compose.yml
- Current max connection size is defined to 151
- try to increase max connections to 1000
https://medium.com/@kauminikg/how-to-increase-max-connections-in-mysql-docker-container-772ae17e3526
=> Increase max Connection Size

app/models/data_resources/resource_modules/media_content.rb, config/initializers/storage_blob_override.rb
model:
- extended file name determination base on the `source_url`
- passed `content_type` as well
model + controller:
- created url with `rails_blob_path` that routes through the rails app and redirects to a fileserver url, see https://msp-greg.github.io/rails_gem_5/file.active_storage_overview.html#linking-to-files
credentials:
- added the mainserver url in credentials in order to be used for the attachment url creation
routes:
- added constraint to not run into 404 for paths with /rails/active_storage, like the new urls that will look like: http://localhost:4000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40868bae79837b0d276e11960f70d3a16d527c55/header_panda_baumstamm_mitte.jpg
SVA-738
=> fix(attachment urls): return readable urls

config/initializers/doorkeeper.rb
Die Konfiguration der Access Token Ablaufzeit wurde von 2 auf 24 Stunden erhöht. Dies ermöglicht eine längere Verwendung des Access Tokens, sodass lang laufende Imports möglich sind.
=> Erhöhung der Access Token Ablaufzeit

docker-compose.yml
Die Version mysql:5.7.21 gibt es nicht mehr und verursacht somit bei builds Probleme. Wir aktualisieren hiermit auf die lates 5.7. Version die derzeit mysql:5.7.42 ist
Danach sollten auch die automatisierten Backups wieder laufen.
=> Update auf neueste Patchversion von 5.7

config/application.rb
Implementation of German as the standard translation language, with a robust fallback mechanism to English in case the German translation is missing, for efficient handling of I18n::MissingTranslation errors
SVA-285
=> Setting German as default language with English as fallback

spec/mailers/previews/defect_report_mailer_preview.rb, spec/mailers/previews/noticeboard_mailer_preview.rb
The first_or_create method merely checks if a StaticContent object exists or not. On the other hand, find_or_create_by will check if an object exists with specific arguments, and if it doesn't, it will create one using these arguments as well.
=> fix: first_or_create to find_or_create_by

app/graphql/mutations/create_event_record.rb, app/graphql/types/query_types/event_record_type.rb, app/models/data_resources/event_record.rb, app/services/recurring_dates_for_event_service.rb, db/migrate/20230803145654_add_recurrings_to_event_records.rb, db/schema.rb, spec/factories/event_records.rb, spec/models/event_record_spec.rb
This PR introduces new event fields for describing a recurring pattern. Based on this pattern we can create `fixed_date`s for events dynamically. There is a new service that gets called, if recurring dates should be stored in the data base.
The pattern is based on three fields: `recurring_weekdays`, `recurring_type` and `recurring_interval`.
The weekdays are selectable for weekly repetitions and are described with numbers from 0 to 6 for Monday to Sunday.
The type describes the daily, weekly, monthly or yearly repetition based on a number from 0 to 3.
The interval indicates how often the repetition should occur (every two days? every four weeks? every year?).
Christmas every year from 24th December 2023 to 24th December 2073:
- `recurring_weekdays` = nil
- `recurring_type` = 3
- …
=> feat(event): recurring dates

app/models/data_resources/event_record.rb
der Scope Upcomming könnte bisher nicht mit einem anderen Scope verknüpft werden, weil er neu suchte (wie ein :unscoped) und ein neues ActiveRecord::Relation-Objekt zurückgegeben hat.
Durch die Anpassung wird der Scope mit anderen verkettbar und der Filter der bereits existiert wird weiterhin berücksichtigt. bsp.: Category.first.event_records.upcoming
SVA-1154
=> fix(scope): make scope upcoming chainable

app/graphql/types/query_type.rb, app/services/resource_service.rb
:upcoming ist in event_records folgendermaßen definiert:
```
scope :upcoming, lambda { |current_user = nil|
event_records = if current_user.present?
filtered_for_current_user(current_user)
else
all
end
...
```
d.h.: Wenn es keinen `current_user` gibt, dann wir immer `:all` zurückgeliefert. Das führt dazu, dass die Scopes `:filtered_for_current_user` und bei SaaS zusätzlich `:by_data_provider` nicht ausgeführt werden und es somit keine Filterung auf die DataProvider und damit bei SaaS auch nicht auf die Municipality erfolgen würde.
SVA-1174
=> fix: scope check for current_user

app/models/data_resources/event_record.rb
An external/new EventRecord coming by an Importer does not have an addressable_id to compare.
With this fix, "less" duplicates schould be imported from now on.
SVA-1153
=> fix: Compare to EventRecords with address data

app/graphql/resolvers/news_items_search.rb
- added `exclude_mowas_regional_keys` filter for news items searches in GraphQL to be able to return data without certain MoWaS regional keys
SVAK-37
=> feat(news items): exclude MoWaS regional keys

app/controllers/notification/devices_controller.rb, app/graphql/mutations/send_push_notification.rb, app/graphql/resolvers/news_items_search.rb, app/graphql/types/input_types/push_notification_data_input.rb, app/jobs/send_single_push_notification_job.rb, app/models/data_resources/news_item.rb, app/models/notification/device.rb, app/services/push_notification.rb, app/views/notification/devices/_notification_device.json.jbuilder, db/migrate/20231018112623_add_exclude_mowas_regional_keys_to_notification_devices.rb, db/schema.rb, spec/factories/notification_devices.rb, spec/models/notification/device_spec.rb
- added `exclude_mowas_regional_keys` for push notification devices like `exclude_data_provider_ids` with serializing as array to save regional keys where devices do not want to get push notifications for
- added passing the `payload` of news items to the push notification options data object in order to process contained regional keys
- adjusted logics to check for data in push notification options and building of database query to exclude notification devices
- added possibility to pass regional keys per payload in push notification GraphQL mutation
|mobile-app interface|database example with two regional keys|GraphQL example for sending push|resulting database query|
|---|---|---|---|
|<img width="386" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-mainser …
=> feat(push notifications): exclude MoWaS regional keys

db/seeds.rb
with this update, you can directly log into the cms without changing the user role to admin and give rights in the cms for the data provider. this enhancement simplifies the initial setup process.
SVA-1251
=> update(seeds): add admin role and data provider to user

app/graphql/resolvers/event_records_search.rb, app/graphql/types/query_types/event_record_type.rb, app/models/data_resources/event_record.rb, app/models/data_resources/resource_modules/fixed_date.rb, app/models/data_resources/resource_modules/lunch.rb, app/services/recurring_dates_for_event_service.rb
- each date of an event should be presented as an own event though the api
- this is achieved with adjustment of the sql and adding a new field `date` in GraphQL which holds one date of all dates and all events are returned multiple times depending on their number of dates
- the resolver is updated in a way, that the old logic is still working
- if the query contains the new `date`, the new scope is used with the specific select which than requests each date
- if the query does not contain the new `date` the old scope is used and events are returned once like before
SVAK-25
---
the request can take longer now, as more events will be returned. if one event is recurring and has hundreds of dates, hundreds of events will result. this was the wish, as it is the only way to display every date …
=> feat(events): return event records for each date
